# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMvG3__1sYzi6ZII2vvJ9nMaSwWPe7ds
"""

import pandas as pd
baza={
    "FISH":["Qadanova Zulayho","Xalilov Durbek","Arabboyev A.A","Turdimatov M.M","Xonto'rayev S.I","Abdullayeva M.R","Jo'rayeva G.F","Jo'rayeva G.F"],
    "Fan nomi":["Sun'iy' intellekt", "Sun'iy intellekt","Kiberxafsizlik","Kiberxafsizlik","Ma'lumotlar tuzulmasi va algoritmlar","Ma'lumotlar tuzulmasi va algoritmlar","Elektronika va sxemalar","Elektronika va sxemalar"],
    "mashg'ulot turi":["amaliy", "ma'ruza","amaliy", "ma'ruza","amaliy","ma'ruza","amaliy","ma'ruza"],
    "kafedrasi":["Axborot texnologiyalari","Axborot texnologiyalari","Axborot texnologiyalari","Axborot texnologiyalari","Axborot texnologiyalari","Axborot texnologiyalari","Tabiy fanlar","Tabiy fanlar"]
}
db=pd.DataFrame(baza)
print(db)

db.to_excel("teachers.xlsx")